/*
 * objective =>  create a new user in DB:
 * create a user, you must specify an email and a password
 * If the email is missing, return an error Missing email with a status code 400
 * If the password is missing, return an error Missing password with a status
   code 400
 * If the email already exists in DB, return an error Already exist with a
   status code 400
 * The password must be stored after being hashed in SHA1
 * The endpoint is returning the new user with only the email and the id
   (auto generated by MongoDB) with a status code 201
 * The new user must be saved in the collection users:
    email: same as the value received
    password: SHA1 value of the value received
 */

import sha1 from 'sha1';
import { ObjectID } from 'mongodb';
import dbClient from '../utils/db';
import redisClient from '../utils/redis';

class UsersController {
  static async postNew(request, response) {
    const { email } = request.body;
    const { password } = request.body;
    if (!email) return response.status(400).json({ error: 'Missing email' });
    if (!password) return response.status(400).json({ error: 'Missing password' });

    const users = await dbClient.db.collection('users');
    const emailExist = users.findOne({ email });
    if (emailExist) return response.status(400).json({ error: 'Already exist' });

    const hashPassword = sha1(password);
    const user = users.insertOne({ email, password: hashPassword });
    return response.status(201).json({ id: user.insertedId, email });
  }

  static async getMe(request, response) {
    const token = request.header('X-Token');
    const key = `auth_${token}`;
    const userId = await redisClient.get(key);
    if (userId) {
      const users = dbClient.db.collection('users');
      const idObject = new ObjectID(userId);
      users.findOne({ _id: idObject }, (err, user) => {
        if (user) {
          response.status(200).json({ id: userId, email: user.email });
        } else {
          response.status(401).json({ error: 'Unauthorized' });
        }
      });
    } else {
      console.log('Hupatikani!');
      response.status(401).json({ error: 'Unauthorized' });
    }
  }
}

module.exports = UsersController;
